name: "Deploy - To Nexus On Github Release"
on:
  release:
    types: [released]

jobs:
  Deploy:
    uses: MOV-AI/.github/.github/workflows/cpp-workflow.yml@feature/dp-1360-add-argument-publishing-repo-to-cpp-workflow
    with:
      release: 'true'
      prod_publish_repos: '["ppa-public"]'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      auto_commit_pwd: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}