name: "Deploy - On branch main/release Push"
on:
  push:
    branches:
      - main
      - 'releases/**'

    paths-ignore:
      - '**/changelog'

jobs:
  Deploy:
    uses: MOV-AI/movai-gz-sensors/.github/workflows/ignition-workflow.yml@feature/dp-1360-add-deploy-workflow
    with:
      deploy: 'true'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      auto_commit_pwd: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}